### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by danielnaber** [lenny93/ns-grammarcheck-plugin#1]
for danielnaber:

- [x] As `addSuggestionForError` adds the error, we also need a reset call - maybe `errorsFound` could do that? As it is now, with every re-check of the text, the suggestions get repeated again and again in the menu. -> happens only with my add-on, not with demo add-on

for lenny93:

- [x] Something broke with the suggestions: Selecting a suggestion replaces with whitespace, if I keep trying, I get a crash. -> happens only with my add-on, not with demo add-on -> caused by delay, see comment
- [x] As corrections are optional, errors that have no correction currently also have no message, because it's shown on hover. Not sure how to solve that. We maybe could introduce an artifical `<no suggestion>` entry for those errors.
- [x] The text I get in the add-on has duplicated spaces collapsed into a single space. This is a problem as the wrong error position is highlighted then.
- [x] Error underline should be blue and be about as visible as the spell checker underline, i.e. it either should be not so bold or use a lighter blue
- [x] allow more than one suggestion for one error
- [x] each error has also a short description, this should also be displayed in the context menu
- [ ] once cleaned up, submit to Mozilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1140402

**Comment by lenny93** [comment]
Acknowledged. I'll be working on these today.

**Comment by lenny93** [comment]
https://github.com/lenny93/gecko-dev/commit/5ad9bba3966638ccaf3c9df7abb955921c5cd8c0

**Comment by danielnaber** [comment]
I've updated the issue with some bugs.

**Comment by danielnaber** [comment]
The replacements break if there's a timeout, as shown here: https://github.com/danielnaber/firefox-grammar-add-on/blob/master/index-show-replace-bug.js - this simulates the delay we get when the response comes from a remote server. It makes the replacement not work, and then trying several times, on different errors, finally crash. Setting the delay to 0 doesn't help.

**Comment by lenny93** [comment]
Can you update your code to the latest changes and see if it works now? I didn't do thorough testing but it seems to be working as expected now.

**Comment by danielnaber** [comment]
Your example add-on works now, will try to port this to my real checker.

**Comment by danielnaber** [comment]
Please have another look at https://github.com/danielnaber/firefox-grammar-add-on/blob/master/index-show-replace-bug.js and the comments there - the issue with broken replace still exists, depending on how one calls `setTimeout`. Of course it's just a simulation, but in the end I have a remote call and when that returns I need to parse the result, i.e. I need to specify a handler, so I think I need the second way of `setTimeout` to work, too (see  `index.js` for the real code).

**Comment by lenny93** [comment]
I think I've fixed it: https://github.com/lenny93/gecko-dev/commit/2c656acd762e641bd35539f018fa6d1a8eeadbb9
i wasn't able to see the issue with spaces in the text, and I added the (No suggestion) context menu item.

**Comment by danielnaber** [comment]
You should be able to reproduce the issue with the duplicated spaces when you enter this text in a textarea and then log what `handleWord` gets:

```
This    is a test
```
handleWord gets `This is a test`, with the duplicated spaces removed.

**Comment by lenny93** [comment]
Oh, I see it now.

**Comment by danielnaber** [comment]
How can I call `addSuggestionForError` to not have a suggestion but still set the message for the hover? e.g. I tried `addSuggestionForError(j, "", "my message")` but then the suggestion is empty, with `undefined` it's `null` etc.

**Comment by lenny93** [comment]
I fixed the space issue: https://github.com/lenny93/gecko-dev/commit/020a08ba86f2a0cc75dcd292918f536584e52da3
I'm not sure what you mean on that last issue. Do you want a default menu item for message-only suggestions? Right now if you call addSuggestionForError(j, "", "my message") it's just showing an empty menu item but when you hover it shows the message (at least on Windows).

**Comment by danielnaber** [comment]
Thanks, I can confirm the space issue is fixed. Indeed, if I use "" as a suggestion, I see an empty item with tooltip. But as an empty item is confusing, could we have a special item `(no suggestion)` that cannot be selected by the user and that only exists so the tooltip can be accessed? I guess that's what `label="&grammarNoSuggestion.label;"` in one of your commits is for, but how to use that? I mean if messages can only be added when adding suggestions, we need some kind of `null` suggestion?

**Comment by lenny93** [comment]
Yes, that was actually part of this functionality but I wasn't quite sure how to implement it. On this new commit (https://github.com/lenny93/gecko-dev/commit/8617c5f49092ac9dfc7f089f7390fba392ef43e9) I added the option of calling `addSuggestionForError(j, "", "my message")` so then it shows a disabled item using the label in `toolkit/locales/en-US/chrome/global/textcontext.dtd` and the specified tooltip.

**Comment by danielnaber** [comment]
Thanks, it's working nicely now. I'll close this issue and open new ones for the remaining ideas.
